### ISSUE TITLE
[Bug Report] Panic: disk I/O error after updating docker container

### ISSUE THREAD

**Issue by psociety** [stashapp/stash#1157]
**Describe the bug**
I was on v3 and i decided to update. After the update it stopped working.

**To Reproduce**
1. `docker-compose pull` 
2. `docker-compose up -d stash`
3. `docker logs stash`
4. I didn't edit volume config, i can properly read `config.yml`. Renaming it doesn't fix it yet a new `config.yml` is created.
Restarting the container doesn't fix it either :(
I also tried chowning .stash ownership to a nonroot user.

**Error**
```bash
time="2021-02-28T19:04:12+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003726c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:13+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042780, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:14+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003f06c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:15+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042760, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:16+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004326c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:18+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003969e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:22+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc00038ca20, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:29+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003746e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:42+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004006c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:05:09+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000426680, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:06:00+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003ae9e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:07:01+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004246a0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:08:02+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003906c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
root@homeserver:/storage/delta/media/config# docker restart stash
stash
root@homeserver:/storage/delta/media/config# docker logs stash
time="2021-02-28T19:04:12+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003726c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:13+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042780, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:14+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003f06c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:15+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042760, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:16+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004326c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:18+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003969e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:22+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc00038ca20, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:29+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003746e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:42+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004006c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:05:09+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000426680, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:06:00+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003ae9e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:07:01+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004246a0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:08:02+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003906c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:08:59+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000379180, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:09:00+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc00038ed20, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:09:01+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000374d00, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
root@homeserver:/storage/delta/media/config# docker logs stash
time="2021-02-28T19:04:12+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003726c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:13+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042780, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:14+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003f06c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:15+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc000042760, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:16+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0004326c0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:18+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

goroutine 1 [running]:
github.com/stashapp/stash/pkg/database.Initialize(0xc0003969e0, 0x1c, 0x8)
        /stash/pkg/database/database.go:42 +0x28a
main.main()
        /stash/main.go:18 +0x64
time="2021-02-28T19:04:22+01:00" level=info msg="using config file: /root/.stash/config.yml"
panic: disk I/O error

```

I have other containers running perfectly so it's hard for me to belive it's an actual i/o error.

**Stash Version: (from Settings -> About):** v0.5.0

**Comment by WithoutPants** [comment]
This looks like it's failing to read your database file. Can you verify that the sqlite file is readable in the container?

**Comment by psociety** [comment]
@WithoutPants soz to ask, but how can i do it? It doesn't let me enter it via bash since it's restarting nonstop.
All i can do is read it from outside:
![image](https://user-images.githubusercontent.com/29523682/109469994-18be1100-7a6f-11eb-90eb-b87b7c521d84.png)

(i've changed owner back to root and set the original config.yml)

**Comment by InfiniteTF** [comment]
> @WithoutPants soz to ask, but how can i do it? It doesn't let me enter it via bash since it's restarting nonstop.

Remove `restart: unless-stopped` from the docker compose file. Make sure that the shm/wal files are also writable.

Also, is your database by any chance hosted remotely on a samba share?

**Comment by psociety** [comment]
Nope, the only special thing about my server setup is that those files are under a MergerFS (multiple harddrives content combined to show up in the same path) folder:
https://github.com/trapexit/mergerfs
But they have always been.
Ok, i will try it at night!

**Comment by InfiniteTF** [comment]
> Nope, the only special thing about my server setup is that those files are under a MergerFS (multiple harddrives content combined to show up in the same path) folder:
> https://github.com/trapexit/mergerfs
> But they have always been.
> Ok, i will try it at night!

In the latest stash version we switched to using journaling which has better performance and concurrency, but which is more picky about how the database is accessed. It seems this applies to MergerFS as well, and there's a setting you have to change for it to work: https://github.com/trapexit/mergerfs#plex-doesnt-work-with-mergerfs

**Comment by psociety** [comment]
wtf, i also have plex there and i didn't have this problem (and i've restarted it multiple times too).
I will check it, thanks!

**Comment by psociety** [comment]
@InfiniteTF lool, you were right. I checked my plex settings and i have them on another folder. I didn't remember it :o
Thank you so much for researching the error way better than me!

Closing issue, fixed by @InfiniteTF instructions!!!
