### ISSUE TITLE
[Bug] Refactor config handling

### ISSUE THREAD

**Issue by InfiniteTF** [stashapp/stash#1343]
[Viper is not thread-safe](https://github.com/spf13/viper/issues/268), and the way we're using it can result in panic if something tries to access the config while it's being modified.

I suggest changing the config to unmarshal everything to a struct at init, and serving config values from that with getters. This should be more performant since we're no longer reading from disk and doing a bunch of parsing every time we read a config var. Writes to config should be guarded by a mutex.

[Stack-trace from Belley](https://discord.com/channels/559159668438728723/559159910550732809/836273635278716941):
```
fatal error: concurrent map read and map write

goroutine 1120828 [running]:
runtime.throw(0x157852a, 0x21)
        /usr/local/go/src/runtime/panic.go:774 +0x79 fp=0xc0023ef1e8 sp=0xc0023ef1b8 pc=0x433fe9
runtime.mapaccess2_faststr(0x138aa60, 0xc0003ec840, 0x15425d9, 0xd, 0x2e817a0, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x496 fp=0xc0023ef258 sp=0xc0023ef1e8 pc=0x414f76
github.com/spf13/viper.(*Viper).searchMap(0xc000340a20, 0xc0003ec840, 0xc0015aad30, 0x1, 0x1, 0x0, 0x0)
        /stash/vendor/github.com/spf13/viper/viper.go:557 +0x66 fp=0xc0023ef2a0 sp=0xc0023ef258 pc=0xca4856
github.com/spf13/viper.(*Viper).find(0xc000340a20, 0x15425d9, 0xd, 0x1, 0x15, 0x15)
        /stash/vendor/github.com/spf13/viper/viper.go:1136 +0x399 fp=0xc0023ef3c8 sp=0xc0023ef2a0 pc=0xca7329
github.com/spf13/viper.(*Viper).Get(0xc000340a20, 0x15425d9, 0xd, 0x3, 0xc0002c7b80)
        /stash/vendor/github.com/spf13/viper/viper.go:728 +0x88 fp=0xc0023ef458 sp=0xc0023ef3c8 pc=0xca5138
github.com/spf13/viper.(*Viper).GetString(0xc000340a20, 0x15425d9, 0xd, 0x1527e5c, 0x3)
        /stash/vendor/github.com/spf13/viper/viper.go:793 +0x46 fp=0xc0023ef498 sp=0xc0023ef458 pc=0xca5cb6
github.com/spf13/viper.GetString(...)
        /stash/vendor/github.com/spf13/viper/viper.go:791
github.com/stashapp/stash/pkg/manager/config.(*Instance).GetExternalHost(...)
        /stash/pkg/manager/config/config.go:363
github.com/stashapp/stash/pkg/api.BaseURLMiddleware.func1(0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /stash/pkg/api/server.go:365 +0x17d fp=0xc0023ef558 sp=0xc0023ef498 pc=0x10bb49d
net/http.HandlerFunc.ServeHTTP(0xc0003825a0, 0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef580 sp=0xc0023ef558 pc=0x6e74db
github.com/rs/cors.(*Cors).Handler.func1(0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /stash/vendor/github.com/rs/cors/cors.go:207 +0x1b6 fp=0xc0023ef5d8 sp=0xc0023ef580 pc=0x1072606
net/http.HandlerFunc.ServeHTTP(0xc0003825c0, 0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef600 sp=0xc0023ef5d8 pc=0x6e74db
github.com/go-chi/chi/middleware.StripSlashes.func1(0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /stash/vendor/github.com/go-chi/chi/middleware/strip.go:25 +0xf5 fp=0xc0023ef648 sp=0xc0023ef600 pc=0x106dc95
net/http.HandlerFunc.ServeHTTP(0xc0003825e0, 0x259dd00, 0xc002ef7a40, 0xc000ada100)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef670 sp=0xc0023ef648 pc=0x6e74db
github.com/go-chi/chi/middleware.Compress.func1.1(0x86e1018, 0xc002c98700, 0xc000ada100)
        /stash/vendor/github.com/go-chi/chi/middleware/compress.go:148 +0x1c6 fp=0xc0023ef730 sp=0xc0023ef670 pc=0x106cd26
net/http.HandlerFunc.ServeHTTP(0xc0005d5a70, 0x86e1018, 0xc002c98700, 0xc000ada100)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef758 sp=0xc0023ef730 pc=0x6e74db
github.com/go-chi/chi/middleware.RequestLogger.func1.1(0x259fc80, 0xc000144fc0, 0xc0002fdf00)
        /stash/vendor/github.com/go-chi/chi/middleware/logger.go:46 +0x2c5 fp=0xc0023ef878 sp=0xc0023ef758 pc=0x106d565
net/http.HandlerFunc.ServeHTTP(0xc0005d5aa0, 0x259fc80, 0xc000144fc0, 0xc0002fdf00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef8a0 sp=0xc0023ef878 pc=0x6e74db
github.com/go-chi/chi/middleware.Recoverer.func1(0x259fc80, 0xc000144fc0, 0xc0002fdf00)
        /stash/vendor/github.com/go-chi/chi/middleware/recoverer.go:35 +0xc2 fp=0xc0023ef928 sp=0xc0023ef8a0 pc=0x106db72
net/http.HandlerFunc.ServeHTTP(0xc000382680, 0x259fc80, 0xc000144fc0, 0xc0002fdf00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023ef950 sp=0xc0023ef928 pc=0x6e74db
github.com/stashapp/stash/pkg/api.authenticateHandler.func1.1(0x259fc80, 0xc000144fc0, 0xc0002fde00)
        /stash/pkg/api/server.go:112 +0x797 fp=0xc0023efad0 sp=0xc0023ef950 pc=0x10b9fc7
net/http.HandlerFunc.ServeHTTP(0xc0003826a0, 0x259fc80, 0xc000144fc0, 0xc0002fde00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023efaf8 sp=0xc0023efad0 pc=0x6e74db
github.com/go-chi/chi/middleware.Heartbeat.func1.1(0x259fc80, 0xc000144fc0, 0xc0002fde00)
        /stash/vendor/github.com/go-chi/chi/middleware/heartbeat.go:21 +0x1de fp=0xc0023efb70 sp=0xc0023efaf8 pc=0x106d07e
net/http.HandlerFunc.ServeHTTP(0xc0005d5b00, 0x259fc80, 0xc000144fc0, 0xc0002fde00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b fp=0xc0023efb98 sp=0xc0023efb70 pc=0x6e74db
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000020360, 0x259fc80, 0xc000144fc0, 0xc0029d6b00)
        /stash/vendor/github.com/go-chi/chi/mux.go:82 +0x2b9 fp=0xc0023efc18 sp=0xc0023efb98 pc=0x102e589
net/http.serverHandler.ServeHTTP(0xc000622000, 0x259fc80, 0xc000144fc0, 0xc0029d6b00)
        /usr/local/go/src/net/http/server.go:2831 +0xab fp=0xc0023efc48 sp=0xc0023efc18 pc=0x6ea9cb
net/http.(*conn).serve(0xc001630460, 0x25a3000, 0xc002e64580)
        /usr/local/go/src/net/http/server.go:1919 +0x87c fp=0xc0023effc8 sp=0xc0023efc48 pc=0x6e628c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0023effd0 sp=0xc0023effc8 pc=0x462831
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b

goroutine 1 [select (no cases), 491 minutes]:
main.blockForever()
        /stash/main.go:19 +0x27
main.main()
        /stash/main.go:15 +0x33

goroutine 56 [IO wait]:
internal/poll.runtime_pollWait(0x86e0df8, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc0003206c8, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc000320518, 0xc003696720, 0x1, 0x0, 0xacc)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).acceptOne(0xc000320500, 0xacc, 0xc0000921e0, 0x2, 0x2, 0xc000320518, 0xc, 0x0, 0x0, 0xc000759c5c)
        /usr/local/go/src/internal/poll/fd_windows.go:896 +0xa9
internal/poll.(*FD).Accept(0xc000320500, 0xc000759c70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/internal/poll/fd_windows.go:930 +0x17a
net.(*netFD).accept(0xc000320500, 0xc000759d08, 0x6eb97b, 0xc0006220a0)
        /usr/local/go/src/net/fd_windows.go:193 +0x7b
net.(*TCPListener).accept(0xc00041a520, 0x6eb925, 0x0, 0x4dd7fd)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x39
net.(*TCPListener).Accept(0xc00041a520, 0xc000759d58, 0x18, 0xc000458600, 0x6eae9b)
        /usr/local/go/src/net/tcpsock.go:261 +0x4e
net/http.(*Server).Serve(0xc000622000, 0x259fa00, 0xc00041a520, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2925 +0x287
net/http.(*Server).ListenAndServe(0xc000622000, 0x2a, 0x0)
        /usr/local/go/src/net/http/server.go:2854 +0xbe
github.com/stashapp/stash/pkg/api.Start.func8(0xc0005550d0, 0xc, 0xc0005550a0, 0xe, 0xc000622000)
        /stash/pkg/api/server.go:296 +0x132
created by github.com/stashapp/stash/pkg/api.Start
        /stash/pkg/api/server.go:291 +0x1693

goroutine 204 [select]:
database/sql.(*DB).connectionOpener(0xc0001366c0, 0x25a3000, 0xc000079e40)
        /usr/local/go/src/database/sql/sql.go:1071 +0xef
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:742 +0x131

goroutine 530016 [select]:
database/sql.(*DB).connectionCleaner(0xc0001366c0, 0x6fc23ac00)
        /usr/local/go/src/database/sql/sql.go:969 +0x377
created by database/sql.(*DB).startCleanerLocked
        /usr/local/go/src/database/sql/sql.go:956 +0xae

goroutine 1245528 [IO wait]:
internal/poll.runtime_pollWait(0x944a238, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc000d62448, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc000d62298, 0x241b710, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000d62280, 0xc0006ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:527 +0x31c
net.(*netFD).Read(0xc000d62280, 0xc0006ca000, 0x1000, 0x1000, 0xc0007b19e8, 0x4ea2d4, 0xc000d62280)
        /usr/local/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc001fc9c70, 0xc0006ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x6f
net/http.(*connReader).Read(0xc00332fe90, 0xc0006ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:796 +0xfb
bufio.(*Reader).fill(0xc0038e6a80)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc0038e6a80, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0007b1ad0)
        /usr/local/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc001216460, 0x25a3000, 0xc0023e6480, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:979 +0xb45
net/http.(*conn).serve(0xc001216460, 0x25a3000, 0xc0023e6480)
        /usr/local/go/src/net/http/server.go:1845 +0x6db
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b

goroutine 1278164 [runnable]:
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).keepAlive(0xc000a46420, 0x25a3000, 0xc0033b6000)
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/transport/websocket.go:181
created by github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).run
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/transport/websocket.go:150 +0x165

goroutine 1205288 [IO wait]:
internal/poll.runtime_pollWait(0x9449e28, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc001f6d348, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc001f6d198, 0x241b710, 0xc0006e9708, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc001f6d180, 0xc00100e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:527 +0x31c
net.(*netFD).Read(0xc001f6d180, 0xc00100e000, 0x1000, 0x1000, 0x0, 0xc0006e97d8, 0xc0006e9830)
        /usr/local/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc00460f480, 0xc00100e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x6f
net/http.(*connReader).Read(0xc002759650, 0xc00100e000, 0x1000, 0x1000, 0xc001f6d270, 0x0, 0x5)
        /usr/local/go/src/net/http/server.go:796 +0xfb
bufio.(*Reader).fill(0xc003477e00)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).ReadSlice(0xc003477e00, 0xc001f6d20a, 0x0, 0xc0006e99a8, 0x40e0a0, 0xc00288aa00, 0x100)
        /usr/local/go/src/bufio/bufio.go:359 +0x44
bufio.(*Reader).ReadLine(0xc003477e00, 0xc0006e99b0, 0xc000454000, 0x1b0008, 0x0, 0x0, 0x4ea3c9)
        /usr/local/go/src/bufio/bufio.go:388 +0x3b
net/textproto.(*Reader).readLineSlice(0xc0022a2f30, 0xc00288aa00, 0xc001f6d180, 0x0, 0x0, 0x435e33)
        /usr/local/go/src/net/textproto/reader.go:57 +0x73
net/textproto.(*Reader).ReadLine(...)
        /usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc003477e00, 0x0, 0xc00288aa00, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:1012 +0x99
net/http.(*conn).readRequest(0xc0013bc640, 0x25a3000, 0xc000ac2080, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:982 +0x166
net/http.(*conn).serve(0xc0013bc640, 0x25a3000, 0xc000ac2080)
        /usr/local/go/src/net/http/server.go:1845 +0x6db
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b

goroutine 1218461 [IO wait]:
internal/poll.runtime_pollWait(0x944a168, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc0008366c8, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc000836518, 0x241b710, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000836500, 0xc00099c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:527 +0x31c
net.(*netFD).Read(0xc000836500, 0xc00099c000, 0x1000, 0x1000, 0xc0008599e8, 0x4ea2d4, 0xc000836500)
        /usr/local/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc002aaaaa8, 0xc00099c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x6f
net/http.(*connReader).Read(0xc002d1e6f0, 0xc00099c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:796 +0xfb
bufio.(*Reader).fill(0xc003f38c60)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc003f38c60, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc000859ad0)
        /usr/local/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc00169e280, 0x25a3000, 0xc000691ec0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:979 +0xb45
net/http.(*conn).serve(0xc00169e280, 0x25a3000, 0xc000691ec0)
        /usr/local/go/src/net/http/server.go:1845 +0x6db
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b

goroutine 1191372 [IO wait]:
internal/poll.runtime_pollWait(0x944a8b8, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc001774e48, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc001774c98, 0x241b710, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc001774c80, 0xc00028d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:527 +0x31c
net.(*netFD).Read(0xc001774c80, 0xc00028d000, 0x1000, 0x1000, 0xc0009519e8, 0x4ea2d4, 0xc001774c80)
        /usr/local/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc004133d90, 0xc00028d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x6f
net/http.(*connReader).Read(0xc0020720f0, 0xc00028d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:796 +0xfb
bufio.(*Reader).fill(0xc002e26a20)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc002e26a20, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc000951ad0)
        /usr/local/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc001630320, 0x25a3000, 0xc0013d3c80, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:979 +0xb45
net/http.(*conn).serve(0xc001630320, 0x25a3000, 0xc0013d3c80)
        /usr/local/go/src/net/http/server.go:1845 +0x6db
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b

goroutine 1282066 [IO wait]:
internal/poll.runtime_pollWait(0x86e0848, 0x72, 0x258a480)
        /usr/local/go/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc000a10948, 0x72, 0x1181900, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2e591f8, 0xc000a10798, 0x241b710, 0xc000a108a0, 0x0, 0xc000a10870)
        /usr/local/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000a10780, 0xc003580000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:527 +0x31c
net.(*netFD).Read(0xc000a10780, 0xc003580000, 0x1000, 0x1000, 0x0, 0x0, 0xc000848b38)
        /usr/local/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000402a18, 0xc003580000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x6f
bufio.(*Reader).fill(0xc001638000)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001638000, 0x2, 0x0, 0x8, 0x0, 0x0, 0x5)
        /usr/local/go/src/bufio/bufio.go:138 +0x56
github.com/gorilla/websocket.(*Conn).read(0xc0021d2c60, 0x2, 0x0, 0x0, 0xc000848c68, 0x0, 0x0)
        /stash/vendor/github.com/gorilla/websocket/conn.go:370 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0021d2c60, 0x0, 0x0, 0x1)
        /stash/vendor/github.com/gorilla/websocket/conn.go:798 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc0021d2c60, 0x2e63ba0, 0xc003716008, 0x1, 0x10000c000848da8, 0x2e63ba0)
        /stash/vendor/github.com/gorilla/websocket/conn.go:980 +0xa7
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).readOp(0xc000a46420, 0x1ad59ba6f565)
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/transport/websocket.go:295 +0x4b
github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).run(0xc000a46420)
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/transport/websocket.go:155 +0x1a2
github.com/99designs/gqlgen/graphql/handler/transport.Websocket.Do(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2419818, ...)
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/transport/websocket.go:85 +0x3e1
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc000382480, 0x259dd00, 0xc002f880a0, 0xc0014d9700)
        /stash/vendor/github.com/99designs/gqlgen/graphql/handler/server.go:115 +0x208
net/http.HandlerFunc.ServeHTTP(0xc0002b47a0, 0x259dd00, 0xc002f880a0, 0xc0014d9600)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000020360, 0x259dd00, 0xc002f880a0, 0xc0014d9600)
        /stash/vendor/github.com/go-chi/chi/mux.go:425 +0x27f
net/http.HandlerFunc.ServeHTTP(0xc0002b47b0, 0x259dd00, 0xc002f880a0, 0xc0014d9600)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/stashapp/stash/pkg/api.BaseURLMiddleware.func1(0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /stash/pkg/api/server.go:372 +0x2df
net/http.HandlerFunc.ServeHTTP(0xc0003825a0, 0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/rs/cors.(*Cors).Handler.func1(0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /stash/vendor/github.com/rs/cors/cors.go:207 +0x1b6
net/http.HandlerFunc.ServeHTTP(0xc0003825c0, 0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi/middleware.StripSlashes.func1(0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /stash/vendor/github.com/go-chi/chi/middleware/strip.go:25 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc0003825e0, 0x259dd00, 0xc002f880a0, 0xc0014d8b00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi/middleware.Compress.func1.1(0x86e1018, 0xc003d66500, 0xc0014d8b00)
        /stash/vendor/github.com/go-chi/chi/middleware/compress.go:148 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc0005d5a70, 0x86e1018, 0xc003d66500, 0xc0014d8b00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi/middleware.RequestLogger.func1.1(0x259fc80, 0xc000796000, 0xc0014d8a00)
        /stash/vendor/github.com/go-chi/chi/middleware/logger.go:46 +0x2c5
net/http.HandlerFunc.ServeHTTP(0xc0005d5aa0, 0x259fc80, 0xc000796000, 0xc0014d8a00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi/middleware.Recoverer.func1(0x259fc80, 0xc000796000, 0xc0014d8a00)
        /stash/vendor/github.com/go-chi/chi/middleware/recoverer.go:35 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc000382680, 0x259fc80, 0xc000796000, 0xc0014d8a00)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/stashapp/stash/pkg/api.authenticateHandler.func1.1(0x259fc80, 0xc000796000, 0xc0014d8900)
        /stash/pkg/api/server.go:112 +0x797
net/http.HandlerFunc.ServeHTTP(0xc0003826a0, 0x259fc80, 0xc000796000, 0xc0014d8900)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi/middleware.Heartbeat.func1.1(0x259fc80, 0xc000796000, 0xc0014d8900)
        /stash/vendor/github.com/go-chi/chi/middleware/heartbeat.go:21 +0x1de
net/http.HandlerFunc.ServeHTTP(0xc0005d5b00, 0x259fc80, 0xc000796000, 0xc0014d8900)
        /usr/local/go/src/net/http/server.go:2036 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000020360, 0x259fc80, 0xc000796000, 0xc0014d8600)
        /stash/vendor/github.com/go-chi/chi/mux.go:82 +0x2b9
net/http.serverHandler.ServeHTTP(0xc000622000, 0x259fc80, 0xc000796000, 0xc0014d8600)
        /usr/local/go/src/net/http/server.go:2831 +0xab
net/http.(*conn).serve(0xc0007b3220, 0x25a3000, 0xc003d66000)
        /usr/local/go/src/net/http/server.go:1919 +0x87c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x38b```

**Comment by WithoutPants** [comment]
Related to #83
