### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by hmahler2** [stashapp/stash#1738]
**Describe the bug**
stash-osx now fails to launch with the newest builds.

**Stash Version: (from Settings -> About):**
v0.9.0-2-g04e146f2 is functioning. Later builds don't start.

**Desktop (please complete the following information):**
 - OS: Mac 10.11.6

**Additional context**
```

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/hmahler/.stash/stash-osx
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/hmahler/.stash/stash-osx
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff66216075 m=0 sigcode=1

goroutine 0 [idle]:
runtime.walltime()
	runtime/sys_darwin.go:279 +0x47 fp=0xc0000d5570 sp=0xc0000d5540 pc=0x4055387
time.now()
	runtime/timestub.go:19 +0x19 fp=0xc0000d55a0 sp=0xc0000d5570 pc=0x40667b9
time.Now()
	time/time.go:1074 +0x17 fp=0xc0000d55b0 sp=0xc0000d55a0 pc=0x4088d37
github.com/sirupsen/logrus.init.2()
	github.com/sirupsen/logrus@v1.8.1/text_formatter.go:26 +0x17 fp=0xc0000d55c0 sp=0xc0000d55b0 pc=0x42fdad7
runtime.doInit(0x64dab20)
	runtime/proc.go:6498 +0x123 fp=0xc0000d56f8 sp=0xc0000d55c0 pc=0x4045a63
runtime.doInit(0x64d6b80)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5830 sp=0xc0000d56f8 pc=0x40459b1
runtime.doInit(0x64d1b80)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5968 sp=0xc0000d5830 pc=0x40459b1
runtime.doInit(0x64d9ae0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5aa0 sp=0xc0000d5968 pc=0x40459b1
runtime.doInit(0x64daee0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5bd8 sp=0xc0000d5aa0 pc=0x40459b1
runtime.doInit(0x64d02c0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5d10 sp=0xc0000d5bd8 pc=0x40459b1
runtime.doInit(0x64e0180)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5e48 sp=0xc0000d5d10 pc=0x40459b1
runtime.doInit(0x64d6480)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5f80 sp=0xc0000d5e48 pc=0x40459b1
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc0000d5fe0 sp=0xc0000d5f80 pc=0x40387a6
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0000d5fe8 sp=0xc0000d5fe0 pc=0x40698a1

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:350 fp=0xc0000d5510 sp=0xc0000d5508 pc=0x4067660
runtime.libcCall(0x65ecea0, 0xc0000accc0)
	runtime/sys_libc.go:49 +0x66 fp=0xc0000d5540 sp=0xc0000d5510 pc=0x4055a06
runtime.walltime()
	runtime/sys_darwin.go:279 +0x47 fp=0xc0000d5570 sp=0xc0000d5540 pc=0x4055387
time.now()
	runtime/timestub.go:19 +0x19 fp=0xc0000d55a0 sp=0xc0000d5570 pc=0x40667b9
time.Now()
	time/time.go:1074 +0x17 fp=0xc0000d55b0 sp=0xc0000d55a0 pc=0x4088d37
github.com/sirupsen/logrus.init.2()
	github.com/sirupsen/logrus@v1.8.1/text_formatter.go:26 +0x17 fp=0xc0000d55c0 sp=0xc0000d55b0 pc=0x42fdad7
runtime.doInit(0x64dab20)
	runtime/proc.go:6498 +0x123 fp=0xc0000d56f8 sp=0xc0000d55c0 pc=0x4045a63
runtime.doInit(0x64d6b80)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5830 sp=0xc0000d56f8 pc=0x40459b1
runtime.doInit(0x64d1b80)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5968 sp=0xc0000d5830 pc=0x40459b1
runtime.doInit(0x64d9ae0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5aa0 sp=0xc0000d5968 pc=0x40459b1
runtime.doInit(0x64daee0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5bd8 sp=0xc0000d5aa0 pc=0x40459b1
runtime.doInit(0x64d02c0)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5d10 sp=0xc0000d5bd8 pc=0x40459b1
runtime.doInit(0x64e0180)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5e48 sp=0xc0000d5d10 pc=0x40459b1
runtime.doInit(0x64d6480)
	runtime/proc.go:6475 +0x71 fp=0xc0000d5f80 sp=0xc0000d5e48 pc=0x40459b1
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc0000d5fe0 sp=0xc0000d5f80 pc=0x40387a6
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0000d5fe8 sp=0xc0000d5fe0 pc=0x40698a1

rax    0x7fff6624f290
rbx    0x6a06df0
rcx    0x0
rdx    0x0
rdi    0x7fff6624f400
rsi    0x0
rbp    0x7fff5fbff7f0
rsp    0x7fff5fbff7d8
r8     0x7fff6623804c
r9     0xffff8000
r10    0x7fff5fbff5c5
r11    0x7fff6624f400
r12    0x203000
r13    0x203000
r14    0x7fff6624f400
r15    0x2e005667
rip    0x7fff66216075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by InfiniteTF** [comment]
Unfortunately modern versions of go no longer support El Capitan. You'll have to upgrade osx to at least 10.12.

**Comment by kermieisinthehouse** [comment]
It seems @InfiniteTF is correct. I tried messing with the linker to ignore this header but other problems cropped up. https://golang.org/doc/go1.12#darwin

**Comment by SmallCoccinelle** [comment]
El Capitan is 5 years old and got it's last batch of security updates in 2018, fwiw.

That's why most modern software doesn't support it.

**Comment by WithoutPants** [comment]
There's no going back to a previous go version, so I think this can't be fixed. Closing.
