### ISSUE TITLE
[Bug Report] Autotag with forward slash ending tag, container crashes

### ISSUE THREAD

**Issue by sbaak12** [stashapp/stash#1752]
**Describe the bug**
When running auto-tag while a \ is at the end of a tag causes container to crash.  \\( makes the following ) invalid. It was specifically saved as inno\

**To Reproduce**
1. Create a tag with \ at the end
2. Run auto-tag
4. See error (below)

**Expected behavior**
Auto-tag to run.

**Screenshots**
N/A

**Stash Version: (from Settings -> About):**
Version: v0.9.0-44-gf292238e
Build time: 2021-09-21 12:02:13

**Desktop (please complete the following information):**
 - OS: Windows, running on:Debian GNU/Linux 11 (bullseye)
 - Browser: Chrome (up to date)

**Additional context**
Not a huge deal, pretty random. 

Maybe some rule if \ in tag text then \\\ in the expression. 

```
panic: regexp: Compile(`(?:^|_|[^\w\d])inno\(?:$|_|[^\w\d])`): error parsing regexp: unexpected ): `(?:^|_|[^\w\d])inno\(?:$|_|[^\w\d])` [recovered]
        panic: regexp: Compile(`(?:^|_|[^\w\d])inno\(?:$|_|[^\w\d])`): error parsing regexp: unexpected ): `(?:^|_|[^\w\d])inno\(?:$|_|[^\w\d])`
goroutine 127888 [running]:
github.com/stashapp/stash/pkg/models.WithTxn.func1()
        github.com/stashapp/stash/pkg/models/transaction.go:34 +0xc7
panic({0x1224aa0, 0xc0001f5b00})
        runtime/panic.go:1038 +0x215
regexp.MustCompile({0xc002f02180, 0x23})
        regexp/regexp.go:311 +0xbb
github.com/stashapp/stash/pkg/autotag.nameMatchesPath({0xc000b82608, 0xc000554000}, {0xc000cf2960, 0x44})
        github.com/stashapp/stash/pkg/autotag/tagger.go:66 +0xd0
github.com/stashapp/stash/pkg/autotag.getMatchingTags({0xc000cf2960, 0x44}, {0x21748f0, 0xc0006e6ed0})
        github.com/stashapp/stash/pkg/autotag/tag.go:21 +0x10c
github.com/stashapp/stash/pkg/autotag.(*tagger).tagTags(0xc00155bd58, {0x21748f0, 0xc0006e6ed0}, 0xc00155bd40)
        github.com/stashapp/stash/pkg/autotag/tagger.go:165 +0x65
github.com/stashapp/stash/pkg/autotag.SceneTags(0x1, {0x217a4f8, 0xc0006e6ea0}, {0x21748f0, 0xc0006e6ed0})
        github.com/stashapp/stash/pkg/autotag/scene.go:114 +0xff
github.com/stashapp/stash/pkg/manager.(*autoTagSceneTask).Start.func1({0x216c5d0, 0xc0004c0258})
        github.com/stashapp/stash/pkg/manager/task_autotag.go:657 +0x1d2
github.com/stashapp/stash/pkg/models.WithTxn({0x215b578, 0xc0004c0258}, 0xc000d43980)
        github.com/stashapp/stash/pkg/models/transaction.go:44 +0xdb
github.com/stashapp/stash/pkg/sqlite.(*TransactionManager).WithTxn(0xc002f3c8f0, {0x215b070, 0xc000048038}, 0xc000d99f50)
        github.com/stashapp/stash/pkg/sqlite/transaction.go:205 +0x105
github.com/stashapp/stash/pkg/manager.(*autoTagSceneTask).Start(0xc00026c000, 0xc00132c910)
        github.com/stashapp/stash/pkg/manager/task_autotag.go:645 +0xb7
created by github.com/stashapp/stash/pkg/manager.(*autoTagFilesTask).processScenes
        github.com/stashapp/stash/pkg/manager/task_autotag.go:487 +0x1b6
```

**Comment by kermieisinthehouse** [comment]
While I can't reproduce a crash of stash, I can reproduce an error that stops auto-tagging. I've tested that my PR #1753 fixes this error, and should probably fix the crash.
