### ISSUE TITLE
Filesystem monitoring

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#191]
Feature enhancement suggestion to implement filesystem monitoring.

The different platforms have APIs for monitoring the filesystem for changes. This allows you to watch a filesystem tree for renames, movement within the tree, deletions, additions, or other modifications. The nice thing is that it requires no polling to keep the file paths up to date. If a file is renamed, the app immediately gets and event and can update the database with minimal processing requirements.

There are, unfortunately, quite a few shortcomings, such as incompatible APIs between platforms, limits on the number of watches, no way of monitoring network shares, etc. That said, I still think it's worth checking out since it can make working with a collection much smoother.

There is a cross-platform library for go which supports linux/mac/windows. I haven't looked at the limitations of the mac/windows implementations, but hopefully it's not too bad: https://github.com/fsnotify/fsnotify

More info about the APIs:
https://en.wikipedia.org/wiki/Inotify
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw

**Comment by Leopere** [comment]
This would be good to double-check the changes that the tagging system has done what was requested of it.

**Comment by spirillen** [comment]
This is a old issue, yet it seems to be only partly implanted... For debian|ubuntu users there are lacking pything pkg to fullfill this implantation

```log
2026-01-30T19:16:44.925094915+01:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"192.0.2.0:36488","requestID":"hostname/dKZsomethingsomethingvHwVZQN-000289","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://hostname.local:9999/graphql"} httpResponse={"bytes":26,"elapsed":0.112865,"status":200} service=stash
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] error: externally-managed-environment
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] × This environment is externally managed
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] ╰─> To install Python packages system-wide, try apt install
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     python3-xyz, where xyz is the package you are trying to
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     install.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     If you wish to install a non-Debian-packaged Python package,
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     create a virtual environment using python3 -m venv path/to/venv.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     sure you have python3-full installed.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     If you wish to install a non-Debian packaged Python application,
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     it may be easiest to use pipx install xyz, which will manage a
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     virtual environment for you. Make sure you have pipx installed.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     See /usr/share/doc/python3.12/README.venv for more information.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] hint: See PEP 668 for the detailed specification.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] error: externally-managed-environment
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] × This environment is externally managed
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] ╰─> To install Python packages system-wide, try apt install
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     python3-xyz, where xyz is the package you are trying to
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     install.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     If you wish to install a non-Debian-packaged Python package,
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     create a virtual environment using python3 -m venv path/to/venv.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     sure you have python3-full installed.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     If you wish to install a non-Debian packaged Python application,
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     it may be easiest to use pipx install xyz, which will manage a
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     virtual environment for you. Make sure you have pipx installed.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor]     See /usr/share/doc/python3.12/README.venv for more information.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
ERRO[2026-01-30 19:16:48] [Plugin / FileMonitor] hint: See PEP 668 for the detailed specification.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] error: externally-managed-environment
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] × This environment is externally managed
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] ╰─> To install Python packages system-wide, try apt install
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     python3-xyz, where xyz is the package you are trying to
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     install.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     If you wish to install a non-Debian-packaged Python package,
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     create a virtual environment using python3 -m venv path/to/venv.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     sure you have python3-full installed.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     If you wish to install a non-Debian packaged Python application,
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     it may be easiest to use pipx install xyz, which will manage a
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     virtual environment for you. Make sure you have pipx installed.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     See /usr/share/doc/python3.12/README.venv for more information.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] hint: See PEP 668 for the detailed specification.
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] Traceback (most recent call last):
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]   File "/home/usernameX/.stash/plugins/community/filemonitor/filemonitor.py", line 14, in <module>
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     from StashPluginHelper import StashPluginHelper
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]   File "/home/usernameX/.stash/plugins/community/filemonitor/StashPluginHelper.py", line 18, in <module>
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor]     from stashapi.stashapp import StashInterface
ERRO[2026-01-30 19:16:49] [Plugin / FileMonitor] ModuleNotFoundError: No module named 'stashapi'
ERRO[2026-01-30 19:16:49] runPluginOperation: input: runPluginOperation exit status 1
```

Using static build v0.30.1 on ubuntu 24 LTS

**Comment by DogmaDragon** [comment]
@spirillen that is plugin issue, not Stash issue.

**Comment by Gykes** [comment]
After discussion with the other devs we came to this conclusion for https://github.com/stashapp/stash/pull/6299#issuecomment-4071515119

With that in mind I will close this issue in favor of pointing users to using plugins for this issue.
