### ISSUE TITLE
[Bug Report] invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by wranglatang** [stashapp/stash#4030]
After updating to v0.22.0 when I run the identify task I get the below error in the log. Reading though other bug reports, it looks like this issue has been reported before. I tried deleting the problem file but the error appears again with the next file in the list.

```log
ERRO[2023-08-14 16:37:16] panic in job 1 - Identifying...: runtime error: invalid memory address or nil pointer dereference 
ERRO[2023-08-14 16:37:16] goroutine 115 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/stashapp/stash/pkg/job.(*Manager).executeJob.func1()
        github.com/stashapp/stash/pkg/job/manager.go:200 +0x165
panic({0x15368fba8200, 0x15369062e1f0})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/pkg/txn.withTxn.func1()
        github.com/stashapp/stash/pkg/txn/transaction.go:68 +0x2fc
panic({0x15368fba8200, 0x15369062e1f0})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/pkg/models.(*ScrapedStudio).ToStudio(0xc000532050, {0x0, 0x0}, 0x0?)
        github.com/stashapp/stash/pkg/models/model_scraped_item.go:33 +0xb9
github.com/stashapp/stash/internal/identify.createMissingStudio({0x15368fd62de0, 0xc0006639e0}, {0x0?, 0x6?}, {0x15368fd6e560?, 0xc0000aa840?}, 0xc000532050)
        github.com/stashapp/stash/internal/identify/studio.go:66 +0x613
github.com/stashapp/stash/internal/identify.sceneRelationships.studio({{0x153665e1d508, 0xc000292150}, {0x15368fd6e560, 0xc0000aa840}, {0x153665e1d558, 0xc0000aa7e0}, {0x153665e1d580, 0xc0000aa8a0}, 0xc00014ec40, 0xc000418cc0, ...}, ...)
        github.com/stashapp/stash/internal/identify/scene.go:70 +0x19c
github.com/stashapp/stash/internal/identify.(*SceneIdentifier).getSceneUpdater(0xc0004d19c8, {0x15368fd62de0, 0xc0006639e0}, 0xc00014ec40, 0xc000418cc0)
        github.com/stashapp/stash/internal/identify/identify.go:189 +0x528
github.com/stashapp/stash/internal/identify.(*SceneIdentifier).modifyScene.func1({0x15368fd62de0, 0xc0006639e0})
        github.com/stashapp/stash/internal/identify/identify.go:277 +0x1ad
github.com/stashapp/stash/pkg/txn.withTxn({0x15368fd62de0, 0xc0002cfc50}, {0x15368fd63b38, 0xc0002e7a00}, 0xc0004d0f38, 0x80?, 0x1)
        github.com/stashapp/stash/pkg/txn/transaction.go:92 +0x17b
github.com/stashapp/stash/pkg/txn.WithTxn(...)
        github.com/stashapp/stash/pkg/txn/transaction.go:39
github.com/stashapp/stash/internal/identify.(*SceneIdentifier).modifyScene(0xc0004d19c8?, {0x15368fd62de0?, 0xc0002cfc50?}, {0x15368fd63b38?, 0xc0002e7a00?}, 0xc00014ec40?, 0x15368fae01d8?)
        github.com/stashapp/stash/internal/identify/identify.go:261 +0xd1
github.com/stashapp/stash/internal/identify.(*SceneIdentifier).Identify(0x15368fd078e0?, {0x15368fd62de0, 0xc0002cfc50}, {0x15368fd63b38, 0xc0002e7a00}, 0xc00014ec40)
        github.com/stashapp/stash/internal/identify/identify.go:86 +0x374
github.com/stashapp/stash/internal/manager.(*IdentifyJob).identifyScene.func1()
        github.com/stashapp/stash/internal/manager/task_identify.go:146 +0x214
github.com/stashapp/stash/pkg/job.(*Progress).ExecuteTask(0xc000442a00, {0xc000173260, 0x5b}, 0xc0004d1b58)
        github.com/stashapp/stash/pkg/job/progress.go:175 +0xcd
github.com/stashapp/stash/internal/manager.(*IdentifyJob).identifyScene(0xc00004f000, {0x15368fd62de0, 0xc0002cfc50}, 0xc00014ec40, {0xc0004024c0, 0x1, 0x1})
        github.com/stashapp/stash/internal/manager/task_identify.go:134 +0x15a
github.com/stashapp/stash/internal/manager.(*IdentifyJob).identifyAllScenes.func1(0x15368fd62de0?)
        github.com/stashapp/stash/internal/manager/task_identify.go:123 +0xa5
github.com/stashapp/stash/pkg/scene.BatchProcess({0x15368fd62de0, 0xc0002cfc50}, {0x153665e19e00, 0xc000292150}, 0x30?, 0xc00044c000?, 0xc0004d1d28)
        github.com/stashapp/stash/pkg/scene/query.go:93 +0x20a
github.com/stashapp/stash/internal/manager.(*IdentifyJob).identifyAllScenes(0xc00004f000, {0x15368fd62de0, 0xc0002cfc50}, {0xc0004024c0, 0x1, 0x1})
        github.com/stashapp/stash/internal/manager/task_identify.go:118 +0x2c5
github.com/stashapp/stash/internal/manager.(*IdentifyJob).Execute.func1({0x15368fd62de0?, 0xc0002cfc50?})
        github.com/stashapp/stash/internal/manager/task_identify.go:57 +0x111
github.com/stashapp/stash/pkg/txn.WithDatabase({0x15368fd62d38?, 0xc000401fc0?}, {0x15368fd5b6c0?, 0xc0003188f0?}, 0xc00060ced0)
        github.com/stashapp/stash/pkg/txn/transaction.go:138 +0x5f
github.com/stashapp/stash/internal/manager.(*IdentifyJob).Execute(0xc00004f000, {0x15368fd62d38, 0xc000401fc0}, 0xc000442a00)
        github.com/stashapp/stash/internal/manager/task_identify.go:55 +0x1cb
github.com/stashapp/stash/pkg/job.(*Manager).executeJob(0xc0002921c0, {0x15368fd62d38, 0xc000401fc0}, 0xc00012f040, 0xc0007ebf90?)
        github.com/stashapp/stash/pkg/job/manager.go:209 +0x1a4
created by github.com/stashapp/stash/pkg/job.(*Manager).dispatch
        github.com/stashapp/stash/pkg/job/manager.go:186 +0x20f 
```

**Comment by Flashy78** [comment]
Looks to be fixed in https://github.com/stashapp/stash/pull/4024

A workaround is to disable creating Studios from Identify.

**Comment by wranglatang** [comment]
Thanks @Flashy78 - Any idea when that fix will be in place?
