### ISSUE TITLE
[Bug Report] Scene Preview Scrubber crashes the site

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#4079]
**Describe the bug**
I have the problem that sometimes, when hovering over the lower part of a scene card Thumbnail, the site crashes with a "Something went wrong". It seems to be associated with the new scrubber of the card that provides control over the preview. 

The output of the Something went wrong:
```
TypeError: Cannot read properties of undefined (reading 'start')
    at be (https://DOMAIN/assets/SceneCard-aa7b2fac.js:1:1408)
    at div
    at Ne (https://DOMAIN/assets/SceneCard-aa7b2fac.js:1:2276)
    at a
    at https://DOMAIN/assets/index-8c4074fa.js:116:12972
    at https://DOMAIN/assets/index-8c4074fa.js:116:13315
    at div
    at div
    at https://DOMAIN/assets/Card-9efd8731.js:1:767
    at Yi (https://DOMAIN/assets/config-a700ba8e.js:1:43568)
    at Ie (https://DOMAIN/assets/SceneCard-aa7b2fac.js:1:3039)
    at div
    at Wn (https://DOMAIN/assets/SceneList-3ca55305.js:1:46690)
    at div
    at i (https://DOMAIN/assets/ItemList-603a1156.js:3:111471)
    at https://DOMAIN/assets/ItemList-603a1156.js:3:115161
    at xn (https://DOMAIN/assets/SceneList-3ca55305.js:1:2357)
    at et (https://DOMAIN/assets/SceneList-3ca55305.js:1:47844)
    at h (https://DOMAIN/assets/Scenes-7f1da84e.js:1:4432)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:9147)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:11097)
    at y (https://DOMAIN/assets/Scenes-7f1da84e.js:1:4561)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:9147)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:11097)
    at Suspense
    at M3 (https://DOMAIN/assets/index-8c4074fa.js:2288:26771)
    at div
    at uae (https://DOMAIN/assets/index-8c4074fa.js:3060:2785)
    at Sre (https://DOMAIN/assets/index-8c4074fa.js:3053:4685)
    at yq (https://DOMAIN/assets/index-8c4074fa.js:141:38640)
    at Suspense
    at pq (https://DOMAIN/assets/index-8c4074fa.js:141:37148)
    at gre (https://DOMAIN/assets/index-8c4074fa.js:3053:4358)
    at t (https://DOMAIN/assets/index-8c4074fa.js:137:4249)
    at M3 (https://DOMAIN/assets/index-8c4074fa.js:2288:26771)
    at T0e (https://DOMAIN/assets/index-8c4074fa.js:3095:37021)
    at p5 (https://DOMAIN/assets/index-8c4074fa.js:87:2618)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:5675)
    at t (https://DOMAIN/assets/index-8c4074fa.js:116:12171)
```
Unfortunately Javascript is a bit unforgiving when minified like this, so another clue I can give is that this s.start is happening on 
secondsToTimestamp.
I am relatively sure that this is due to the scenes in question not having a preview generated (yet). While this is of course not a regular case, it is one that should not break the website.

**To Reproduce**
Steps to reproduce the behavior (probably):
1. Scan a scene without generating supporting files
2. Go to scenes view in Grid view
3. Hover with your mouse over the area where the preview scrubber would appear
4. See the site breaking

**Expected behavior**
Just carry on without showing a preview or a scrubber.

**Stash Version:** c364346a

**Desktop:**
 - OS: Xubuntu 23.04
 - Browser: Chromium
 - Version: 114.0.5735.198

**Comment by yoshnopa** [comment]
Found the culprit, it was not a missing file, sorry for the confusion.

It was due to an old format of .vtt, which had milliseconds in them. This was not readable, leading to an empty scrubber in the videoplayer as well as breaking the site when having trying to view the preview scrubber in the grid view.
Regenerating  those vtt ( Scene Scrubber Sprites + Overwrite existing of course) fixed it for me, as the new vtt had the correct format of course.

Not sure when this format change happen, but I'd assume its been several years, so likely not really fault of the app. Still maybe something to document.

Hopefully this helps a lost soul out there. I will close the ticket.
