### ISSUE TITLE
[Bug Report] memery error when merging scenes with GraphiQL

### ISSUE THREAD

**Issue by SirFlobo** [stashapp/stash#4118]
**Describe the bug**
When trying to merge scenes using GrahiQL an internal error occurs.

Message recieved in the playground

```{
  "errors": [
    {
      "message": "Internal system error. Error <runtime error: invalid memory address or nil pointer dereference>",
      "path": [
        "sceneMerge"
      ]
    }
  ],
  "data": {
    "sceneMerge": null
  }
}
```

Console output from stash:

```ERRO[2023-09-13 00:15:28] runtime error: invalid memory address or nil pointer dereference
goroutine 29143334 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/stashapp/stash/internal/api.Start.func1({0x0?, 0x0?}, {0x13f39c0?, 0x1291240})
        github.com/stashapp/stash/internal/api/server.go:79 +0x89
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x0?, {0x1e2b580, 0xc002adf020}, {0x13f39c0?, 0x1291240?})
        github.com/99designs/gqlgen@v0.17.2/graphql/context_operation.go:114 +0x3e
github.com/stashapp/stash/internal/api.(*executionContext)._Mutation_sceneMerge.func1()
        github.com/stashapp/stash/internal/api/generated_exec.go:24642 +0x6a
panic({0x13f39c0, 0x1291240})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/internal/api.(*mutationResolver).SceneMerge(0xc00304c1b8, {0x1e2b580, 0xc002adf020}, {{0xc00313c7c0, 0x1, 0x1}, {0xc001eb6304, 0x4}, 0x0})
        github.com/stashapp/stash/internal/api/resolver_mutation_scene.go:616 +0x2a6
github.com/stashapp/stash/internal/api.(*executionContext)._Mutation_sceneMerge.func2({0x1e2b580?, 0xc002adf020})
        github.com/stashapp/stash/internal/api/generated_exec.go:24664 +0x131
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x1e2b580?, 0xc002adf020?}, 0xc002adf020?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:72 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Mutation_sceneMerge(0xc00313c740, {0x1e2b580, 0xc002adeff0}, {0xc00271f200?, {0xc00313c760?, 0x1e2b580?, 0xc002332490?}})
        github.com/stashapp/stash/internal/api/generated_exec.go:24662 +0x2e7
github.com/stashapp/stash/internal/api.(*executionContext)._Mutation.func5({0x1e2b580?, 0xc002adeff0?})
        github.com/stashapp/stash/internal/api/generated_exec.go:57106 +0x45
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x1e2b580?, 0xc002adeff0?}, 0x137e880?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:69 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Mutation(0xc00313c740, {0x1e2b580, 0xc002adef60}, {0xc0075e0790, 0x1, 0x1})
        github.com/stashapp/stash/internal/api/generated_exec.go:57109 +0x1275
github.com/stashapp/stash/internal/api.(*executableSchema).Exec.func2({0x1e2b580?, 0xc002adef60?})
        github.com/stashapp/stash/internal/api/generated_exec.go:7981 +0x5b
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x1e2b580, 0xc002adef60})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:106 +0x2b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x1e2b580?, 0xc002adef60?}, 0x137e880?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:66 +0x26
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x1e2b580, 0xc002adef00})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:105 +0x113
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({}, {0x1e28e50, 0xc003f3a140}, 0xc004a50c00, {0x1e28a30, 0xc000a288c0})
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/transport/http_post.go:52 +0x308
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc000110640, {0x1e28e50, 0xc003f3a140}, 0xc004a50c00)
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/server.go:120 +0x212
github.com/stashapp/stash/internal/api.Start.func3({0x1e28e50, 0xc003f3a140}, 0xc003a42078?)
        github.com/stashapp/stash/internal/api/server.go:131 +0xe5
net/http.HandlerFunc.ServeHTTP(0x13e51a0?, {0x1e28e50?, 0xc003f3a140?}, 0xc0005081cd?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00052e360, {0x1e28e50, 0xc003f3a140}, 0xc004a50b00)
        github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x1e2b580?, {0x1e28e50?, 0xc003f3a140?}, 0x1290ab0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api/loaders.Middleware.Middleware.func1({0x1e28e50, 0xc003f3a140}, 0xc004a50a00)
        github.com/stashapp/stash/internal/api/loaders/dataloaders.go:119 +0x846
net/http.HandlerFunc.ServeHTTP(0x1e2b580?, {0x1e28e50?, 0xc003f3a140?}, 0x12906d0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.BaseURLMiddleware.func1({0x1e28e50, 0xc003f3a140}, 0xc004a50900)
        github.com/stashapp/stash/internal/api/server.go:497 +0x342
net/http.HandlerFunc.ServeHTTP(0x1e66d732a18?, {0x1e28e50?, 0xc003f3a140?}, 0xc003f3a140?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/middleware.StripSlashes.func1({0x1e28e50, 0xc003f3a140}, 0xc004a50900)
        github.com/go-chi/chi@v4.0.2+incompatible/middleware/strip.go:25 +0x108
net/http.HandlerFunc.ServeHTTP(0xa?, {0x1e28e50?, 0xc003f3a140?}, 0x3f0df?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/middleware.Compress.func1.1({0x1e6737288a0?, 0xc0008f4940}, 0xc004a50900)
        github.com/go-chi/chi@v4.0.2+incompatible/middleware/compress.go:148 +0x1c2
net/http.HandlerFunc.ServeHTTP(0x14ceb80?, {0x1e6737288a0?, 0xc0008f4940?}, 0x16?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.SecurityHeadersMiddleware.func1({0x1e6737288a0, 0xc0008f4940}, 0x0?)
        github.com/stashapp/stash/internal/api/server.go:465 +0xf4
net/http.HandlerFunc.ServeHTTP(0x3f427?, {0x1e6737288a0?, 0xc0008f4940?}, 0x1290301?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0x1e6737288a0?, 0xc0008f4940?}, 0xc002adeb00?)
        github.com/go-chi/chi/v5@v5.0.0/middleware/recoverer.go:37 +0x83
net/http.HandlerFunc.ServeHTTP(0xc004a50800?, {0x1e6737288a0?, 0xc0008f4940?}, 0x0?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/httplog.Handler.func1.1({0x1e2aa70, 0xc000a18000}, 0xc004a50800)
        github.com/go-chi/httplog@v0.2.1/httplog.go:63 +0x48b
net/http.HandlerFunc.ServeHTTP(0x1e2b580?, {0x1e2aa70?, 0xc000a18000?}, 0x1e180c0?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x1e2aa70, 0xc000a18000}, 0xc004a50700)
        github.com/go-chi/chi/v5@v5.0.0/middleware/request_id.go:76 +0x22d
net/http.HandlerFunc.ServeHTTP(0x1e673cac290?, {0x1e2aa70?, 0xc000a18000?}, 0x30?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x0?, {0x1e2aa70?, 0xc000a18000?}, 0xf8?)
        github.com/go-chi/chi/v5@v5.0.0/chain.go:31 +0x2c
github.com/go-chi/chi/middleware.Recoverer.func1({0x1e2aa70?, 0xc000a18000?}, 0x1e18001?)
        github.com/go-chi/chi@v4.0.2+incompatible/middleware/recoverer.go:35 +0x83
net/http.HandlerFunc.ServeHTTP(0x1e2b580?, {0x1e2aa70?, 0xc000a18000?}, 0x1e180e0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/pkg/session.(*Store).VisitedPluginHandler.func1.1({0x1e2aa70, 0xc000a18000}, 0xc004a50600)
        github.com/stashapp/stash/pkg/session/session.go:166 +0x20d
net/http.HandlerFunc.ServeHTTP(0x1e2b580?, {0x1e2aa70?, 0xc000a18000?}, 0x1e180c0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.authenticateHandler.func1.1({0x1e2aa70, 0xc000a18000}, 0xc004a50500)
        github.com/stashapp/stash/internal/api/authentication.go:109 +0x523
net/http.HandlerFunc.ServeHTTP(0xc000a28500?, {0x1e2aa70?, 0xc000a18000?}, 0xc004a50500?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x1e2aa70, 0xc000a18000}, 0xc004a50500)
        github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1e2aa70?, 0xc000a18000?}, 0xf8?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/middleware.Heartbeat.func1.1({0x1e2aa70?, 0xc000a18000?}, 0x1290301?)
        github.com/go-chi/chi@v4.0.2+incompatible/middleware/heartbeat.go:21 +0x1ab
net/http.HandlerFunc.ServeHTTP(0x1e2b4d8?, {0x1e2aa70?, 0xc000a18000?}, 0x1290310?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00052e360, {0x1e2aa70, 0xc000a18000}, 0xc004a50400)
        github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x296
net/http.serverHandler.ServeHTTP({0x1e26f20?}, {0x1e2aa70, 0xc000a18000}, 0xc004a50400)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0022e4000, {0x1e2b580, 0xc000d009f0})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db
ERRO[2023-09-13 00:15:28] sceneMerge: input: sceneMerge Internal system error. Error <runtime error: invalid memory address or nil pointer dereference>
```

**To Reproduce**

Enter the following command/query into the GraphQL playground, :
`mutation {
  sceneMerge(input:{source:[7036], destination:7037}) { id}
}`

**Expected behavior**
I expect the source scenes to get merged into the destination scene

**Stash Version: (from Settings -> About):**
v0.22.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 116.0.1938.81

**Additional context**

Not sure if this is related, but when I try to send the same request using python and the requests library I get the following response from the server:
`{'errors': [{'message': 'operation  not found'}], 'data': None}`

**Comment by stg-annon** [comment]
the merge endpoint is expecting "values" as well

try with this input:
```json
{ 
	"source": [7036], 
	"destination": 7037, 
	"values": { "id":7037 }
}
```

**Comment by Maista6969** [comment]
The `values` field is not marked as mandatory in the [SceneMergeInput](https://github.com/stashapp/stash/blob/f51ac81749ef7fa7cacac038aefb72fbe1c5abd1/graphql/schema/types/scene.graphql#L260-L269) and it looks like this [extra use of Values](https://github.com/stashapp/stash/blob/f51ac81749ef7fa7cacac038aefb72fbe1c5abd1/internal/api/resolver_mutation_scene.go#L554) was introduced in #3839

Could just move that block of code into the `if input.Values != nil` block a few lines above
