### ISSUE TITLE
Bulk Scene URL scraper (2.1)

### ISSUE THREAD

**Issue by Kev1n121** [stashapp/stash#4429]
**Describe the bug**
I dont know If I am on the right place here for this problem. Sorry If i am on the wrong place. With Bulk Scene URL scraper when I try to start the scrape I am getting this error: 

24-01-07 15:07:16Error   Plugin returned error: exit status 1
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper] ConnectionError: GraphQL query failed:422 - b'{"errors":[{"message":"Cannot query field \\"listSceneScrapers\\" on type \\"Query\\". Did you mean \\"listScrapers\\" or \\"findSceneMarkers\\"?","locations":[{"line":1,"column":8}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}'. Query: query {listSceneScrapers {name scene {urls supported_scrapes}}}. Variables: None
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     raise ConnectionError(
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins\py_plugins\stash_interface.py", line 56, in __callGraphQL
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]                ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     response = self.__callGraphQL(query)
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins\py_plugins\stash_interface.py", line 689, in sceneScraperURLs
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     supported_scrapers = client.sceneScraperURLs()
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins/py_plugins/bulk_url_scraper.py", line 82, in __bulk_scrape
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     __bulk_scrape(
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins/py_plugins/bulk_url_scraper.py", line 196, in bulk_scrape
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     bulk_scrape(client)
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins/py_plugins/bulk_url_scraper.py", line 55, in run
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     run(json_input, output)
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins/py_plugins/bulk_url_scraper.py", line 28, in main
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]     main()
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper]   File "Y:\Stash\Plugins/py_plugins/bulk_url_scraper.py", line 316, in <module>
2024-01-07 15:07:16Error   [Plugin / Bulk Scene URL scraper] Traceback (most recent call last):
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] Scraping scenes
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] Found 0 galleries with scrape tag
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] Found 1267 scenes with scrape tag
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] #############################
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] delay: 3
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] create_missing_movies: False
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] create_missing_studios: True
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] create_missing_tags: False
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] create_missing_performers: True
2024-01-07 15:07:16Info    [Plugin / Bulk Scene URL scraper] ##### Bulk URL Scraper #####

It always worked great for me. Till the last update v0.24.0

Using windows 10 
Stash Version: v0.24.1

**Comment by stg-annon** [comment]
I believe this is the repo that plugin is from https://github.com/niemands/StashPlugins

**Comment by DingDongSoLong4** [comment]
Bug reports for plugins need to go to the repo of the specific plugin (in this case https://github.com/niemands/StashPlugins) and not here.

That repo doesn't seem to have had any activity in a long while though, so I doubt you'll get a response there. Someone else might have written an updated version that works though - I'd recommend you join the Stash [Discord](https://discord.gg/2TsNFKt) and ask there.
