### ISSUE TITLE
[Bug Report] GraphQL query failed in Kodi helper script

### ISSUE THREAD

**Issue by Qlupic** [stashapp/stash#4476]
**Describe the bug**
I get an error when trying to run the Kodi helper script.

**To Reproduce**
1. Download the script to the Stash content folder
2. Make an API key in the Stash app.
3. Edit config.py and add the API key from stash. Leave the rest as is.
4. Run the python script from a CMD window with the arguments: `python kodi-helper.py --inline generate-nfo`

**Expected behavior**
NFOs generated.

**Screenshots**

**Stash Version: (from Settings -> About):**
0.24.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
Not relevant

**Additional context**

Here is the error I am getting:

```
PS Y:\stash\content> python kodi-helper.py --inline generate-nfo
Processing page 1 of 1
Traceback (most recent call last):
  File "Y:\stash\content\kodi-helper.py", line 335, in <module>
    main()
  File "Y:\stash\content\kodi-helper.py", line 32, in main
    generateNFOFiles(args)
  File "Y:\stash\content\kodi-helper.py", line 54, in generateNFOFiles
    scenes = getScenes(i, filter)
             ^^^^^^^^^^^^^^^^^^^^
  File "Y:\stash\content\kodi-helper.py", line 206, in getScenes
    result = __callGraphQL(query, variables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\stash\content\kodi-helper.py", line 333, in __callGraphQL
    raise Exception("GraphQL query failed:{} - {}. Query: {}. Variables: {}".format(response.status_code, response.content, query, variables))
Exception: GraphQL query failed:422 - b'{"errors":[{"message":"Cannot query field \\"path\\" on type \\"Scene\\". Did you mean \\"paths\\" or \\"date\\"?","locations":[{"line":7,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Scene\\". Did you mean \\"rating100\\"?","locations":[{"line":8,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"oshash\\" on type \\"Scene\\".","locations":[{"line":11,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}'. Query:
query findScenes($filter: FindFilterType!, $scene_filter: SceneFilterType!) {
  findScenes(filter: $filter, scene_filter: $scene_filter) {
    scenes {
      id
      title
      path
      rating
      details
      date
      oshash
      paths {
        screenshot
        stream
      }
      studio {
        name
        image_path
      }
      performers {
        name
        image_path
      }
      tags {
        name
      }
      movies {
        movie {
          name
        }
      }
    }
  }
}
. Variables: {'filter': {'per_page': 100, 'page': 1}, 'scene_filter': {}}
```

**Comment by Qlupic** [comment]
Should note I am using Python 3.12.1

Also I don't understand exactly how to install the script. Is it just supposed to run in a terminal window?

**Comment by Maista6969** [comment]
This is a community script so it's issues should not go in the main repository, but [CommunityScripts](https://github.com/stashapp/CommunityScripts)

This error was caused by the migration to v0.24 which removed deprecated fields from the GraphQL API, but I've [pushed an update](https://github.com/stashapp/CommunityScripts/commit/3690daa72fcb4360e519eaf9f3f5b813875695da) that will hopefully address your problem: please try this new version of the kodi-helper script 🙂
