### ISSUE TITLE
[Bug Report] Stash OS Migration Polluted SQLITE Remnants 

### ISSUE THREAD

**Issue by elkorol** [stashapp/stash#4534]
Migrating Stash from Linux to Windows has left entries within the SQLITE file. After assigning Windows paths to the library and rescanning media, having forgot to run clean upon the old Linux paths. 

Left entries within the folder table, most of which were removable by feeding the paths into metadataClean. But zip files, paths of which in the folders table remain even after metadataClean, which throws errors like

error getting folder info for "/data/L-D/FolderName/nora-2nd_1200.zip", not cleaning: internal error getting relative path: Rel: can't make /data/L-D/FolderName/nora-2nd_1200.zip relative to L:.P\OLD.D\CathysCraving\nora-2nd_1200.zip

Upon searching for "nora-2nd_1200.zip" in galleries, within the file info panel. It only reports the Windows path

There are also remanent image objects. Which I'm unsure if they are associated previously to any zip file as they don't belong to any gallery. The image objects are imageless. From the image page clicking into any of them throws this error;

TypeError: Cannot read properties of undefined (reading '__typename')
    at vi (http://localhost:9998/assets/Images-904f0ca4.js:1:9646)
    at pi (http://localhost:9998/assets/Images-904f0ca4.js:1:13201)
    at t (http://localhost:9998/assets/index-09a91901.js:40:9217)
    at t (http://localhost:9998/assets/index-09a91901.js:40:11169)
    at at (http://localhost:9998/assets/Images-904f0ca4.js:1:13470)
    at t (http://localhost:9998/assets/index-09a91901.js:40:9217)
    at t (http://localhost:9998/assets/index-09a91901.js:40:11169)
    at Suspense
    at RP (http://localhost:9998/assets/index-09a91901.js:44:351293)
    at div
    at za2 (http://localhost:9998/assets/index-09a91901.js:54:51420)
    at na2 (http://localhost:9998/assets/index-09a91901.js:49:1224722)
    at UUe (http://localhost:9998/assets/index-09a91901.js:44:116449)
    at Suspense
    at RUe (http://localhost:9998/assets/index-09a91901.js:44:115244)
    at h32 (http://localhost:9998/assets/index-09a91901.js:49:1068302)
    at t (http://localhost:9998/assets/index-09a91901.js:40:75570)
    at RP (http://localhost:9998/assets/index-09a91901.js:44:351293)
    at Zd2 (http://localhost:9998/assets/index-09a91901.js:64:39783)
    at CU (http://localhost:9998/assets/index-09a91901.js:19:184960)
    at t (http://localhost:9998/assets/index-09a91901.js:40:5733)
    at t (http://localhost:9998/assets/index-09a91901.js:40:12243)

For any of these images the GraphQL response is well formed, although it's missing any association to any file within the "files" or "visual_files"

Here is a sample GraphQL response;
{
    "data": {
        "findImage": {
            "id": "738183",
            "title": "",
            "code": "",
            "rating100": null,
            "date": null,
            "urls": [],
            "details": "",
            "photographer": "",
            "organized": false,
            "o_counter": 0,
            "created_at": "2022-12-24T09:43:05Z",
            "updated_at": "2024-02-07T21:44:13Z",
            "files": [],
            "paths": {
                "thumbnail": "http://localhost:9998/image/738183/thumbnail?t=1707342253",
                "preview": "",
                "image": "http://localhost:9998/image/738183/image?t=1707342253",
                "__typename": "ImagePathsType"
            },
            "galleries": [],
            "studio": {
                "id": "109",
                "name": "Retracted",
                "image_path": "http://localhost:9998/studio/109/image?t=1672674716",
                "stash_ids": [
                    {
                        "endpoint": "https://stashdb.org/graphql",
                        "stash_id": "Retracted",
                        "__typename": "StashID"
                    }
                ],
                "parent_studio": null,
                "details": "",
                "rating100": null,
                "aliases": [
                    "Retracted",
                ],
                "__typename": "Studio"
            },
            "tags": [
                {
                    "id": "56528",
                    "name": "IMG TEMP",
                    "aliases": [],
                    "image_path": "http://localhost:9998/tag/56528/image?t=1707342241\u0026default=true",
                    "parent_count": 0,
                    "child_count": 0,
                    "__typename": "Tag"
                }
            ],
            "performers": [
                {
                    "id": "14237",
                    "name": "Michael",
                    "disambiguation": "",
                    "url": "",
                    "gender": "MALE",
                    "twitter": "",
                    "instagram": "",
                    "birthdate": null,
                    "ethnicity": "Caucasian",
                    "country": "",
                    "eye_color": "",
                    "height_cm": null,
                    "measurements": "",
                    "fake_tits": "",
                    "penis_length": null,
                    "circumcised": null,
                    "career_length": "",
                    "tattoos": "",
                    "piercings": "",
                    "alias_list": [],
                    "favorite": false,
                    "ignore_auto_tag": false,
                    "image_path": "http://localhost:9998/performer/14237/image?t=1698829573",
                    "scene_count": 2,
                    "image_count": 109,
                    "gallery_count": 2,
                    "movie_count": 0,
                    "performer_count": 2,
                    "o_counter": 0,
                    "tags": [
                        {
                            "id": "50867",
                            "name": "一Info/Performer: No Country Known",
                            "aliases": [],
                            "image_path": "http://localhost:9998/tag/50867/image?t=1682605188\u0026default=true",
                            "parent_count": 1,
                            "child_count": 0,
                            "__typename": "Tag"
                        }
                    ],
                    "stash_ids": [],
                    "rating100": null,
                    "details": "",
                    "death_date": null,
                    "hair_color": "Brunette",
                    "weight": null,
                    "__typename": "Performer"
                }
            ],
            "visual_files": [],
            "__typename": "Image"
        }
    }
}

**Stash Version: (from Settings -> About):**
v0.24.3

**Desktop (please complete the following information):**
 - OS: Docker Instance of Stash +1 year ago, so unsure Linux version migrating to Windows 11
 - Browser: Chrome
 - Version 121.0.6167.160 (Official Build) (64-bit)

**Comment by elkorol** [comment]
With help from WithoutPants, I got this issue resolved.

For the orphaned linux paths, as some of the entries in the folders table were zip file paths as folders, and they had an entry within the zip_file_id column referencing a zip file, which also had the correct Windows folder path referencing it these needed to be cleared first. 

So I ran this SQL query;
SET path = REPLACE(path, '.zip', ''), zip_file_id = null WHERE folders.path LIKE '/data/%`

I then ran this SQL query to change the Linux paths into Windows paths on the D drive so they would be D\data...
UPDATE folders SET path = 'D:' || REPLACE(path, '/', '\') where folders.path like '/data/%'

I then created a folder called data in the root of my D drive, then on client side of Stash I went into settings > Library > Add Directory > And added the D:\data folder and ensured it was checked for both images and videos. 

Then went to Settings > Tasks > Maintenance > Clean (With dry run not being ticked) > Selective Clean > Added the D:\data path > Clean.

It removed all orphaned folders except one which was still being referenced in an entry in the files table. So in my SQL browser I browsed the data for the folders table.

I found the last orphaned entry and took not of the id which happened to be 57344;

I then ran the SQL query 
DELETE FROM files WHERE parent_folder_id = 57344;

and then ran;
DELETE FROM folders WHERE id = 57344;

The only thing left to do was take care of the file-less images.

The easiest way to do this was first create a temporary studio to assign to the images client side, then go to the images page create a filter: file count is 0. Then select all > Edit and apply the newly created studio.

Taking note of the studio id, which can be found from the url when on the studio page which happened to be 2860.

I then ran the SQL query.
DELETE FROM images WHERE studio_id = 2860

Not always backup. This isn't sure fire as although it's fixed these entries. The Anonymise database task isn't working still for me and I'm not sure if it's related to this issue but worth mentioning.
