### ISSUE TITLE
[Bug Report] Failed to fetch Tags

### ISSUE THREAD

**Issue by Written2001** [stashapp/stash#4755]
**Describe the bug**
While clicking on a saved image filter that includes one or multiple specific tags, or searching for these tags by name I get the error message "Failed to fetch".
Other searches on the tags page are working fine.

Some background: On my setup the "reddit" tag contains sub tags that reach up to 5 levels deep. 
The top level Tag "reddit" (1358) as well as 2/3 Level 2 Tags (1402 and 1403) are returning "Error: Failed to fetch" while accessing them directly via the url https://example.com/tags/1402. The third L2 (/tags/2013) Tag is working fine.

There are three Level 3 sub tags for 1402 two of them are working properly and one is not.
Interestingly instead of failing to fetch the tags page itself on this one stash is showing me the tags page but then fails to fetch the images in the images tab of that tag.

- 1358
|- 1402
|- 1403
|- 2013

**To Reproduce**
1. Go to the tags page
2. Start typing in the search field for example "redd"
3. The loading circle appears
4. Error: Failed to fetch

I'm afraid this is not reproducible and may be specific to me.

**Logs**
<details>

<summary>Output from docker logs</summary>

```
ERRO[2024-04-11 17:34:02] runtime error: invalid memory address or nil pointer dereference 
goroutine 1019897 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/stashapp/stash/internal/api.Initialize.func1({0x0?, 0x20?}, {0x7fe46291b500?, 0x7fe463451230})
        github.com/stashapp/stash/internal/api/server.go:120 +0x89
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x7fe460b9c7ac?, {0x7fe462af4e60, 0xc001224270}, {0x7fe46291b500?, 0x7fe463451230?})
        github.com/99designs/gqlgen@v0.17.2/graphql/context_operation.go:114 +0x3e
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages.func1()
        github.com/stashapp/stash/internal/api/generated_exec.go:32907 +0x6a
panic({0x7fe46291b500, 0x7fe463451230})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/pkg/txn.withTxn.func1()
        github.com/stashapp/stash/pkg/txn/transaction.go:68 +0x2fc
panic({0x7fe46291b500, 0x7fe463451230})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/internal/api.(*queryResolver).FindImages.func1({0x7fe462af4e60, 0xc001224720})
        github.com/stashapp/stash/internal/api/resolver_query_find_image.go:110 +0x30f
github.com/stashapp/stash/pkg/txn.withTxn({0x7fe462af4e60, 0xc001224270}, {0x7fe462af55d0, 0xc0000422d0}, 0xc0014d3b98, 0x2?, 0x1)
        github.com/stashapp/stash/pkg/txn/transaction.go:92 +0x17b
github.com/stashapp/stash/pkg/txn.WithReadTxn(...)
        github.com/stashapp/stash/pkg/txn/transaction.go:52
github.com/stashapp/stash/pkg/models.(*Repository).WithReadTxn(...)
        github.com/stashapp/stash/pkg/models/repository.go:37
github.com/stashapp/stash/internal/api.(*Resolver).withReadTxn(0x8?, {0x7fe462af4e60, 0xc001224270}, 0xc000517c00?)
        github.com/stashapp/stash/internal/api/resolver.go:128 +0x65
github.com/stashapp/stash/internal/api.(*queryResolver).FindImages(0x6?, {0x7fe462af4e60?, 0xc001224270?}, 0xc0014d3c98?, {0x0?, 0x7fe46290d940?, 0x20?}, {0x0, 0x0, 0x0}, ...)
        github.com/stashapp/stash/internal/api/resolver_query_find_image.go:64 +0x14b
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages.func2({0x7fe462af4e60?, 0xc001224270})
        github.com/stashapp/stash/internal/api/generated_exec.go:32929 +0x210
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x7fe462af4e60?, 0xc001224270?}, 0xc001224270?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:72 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages(0xc00099ad20, {0x7fe462af4e60, 0xc001224240}, {0xc000dfe800?, {0xc0018c6000?, 0x4?, 0xc0018c80a0?}})
        github.com/stashapp/stash/internal/api/generated_exec.go:32927 +0x2e7
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func37({0x7fe462af4e60?, 0xc001224240?})
        github.com/stashapp/stash/internal/api/generated_exec.go:61539 +0xae
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x7fe462af4e60?, 0xc001224240?}, 0xc00099ad80?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:69 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func38({0x7fe462af4e60?, 0xc001224240?})
        github.com/stashapp/stash/internal/api/generated_exec.go:61547 +0x32
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func39()
        github.com/stashapp/stash/internal/api/generated_exec.go:61551 +0x25
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc0018c6050)
        github.com/99designs/gqlgen@v0.17.2/graphql/fieldset.go:34 +0x96
github.com/stashapp/stash/internal/api.(*executionContext)._Query(0xc00099ad20, {0x7fe462af4e60, 0xc0012241b0}, {0xc0018e97e0, 0x1, 0x1})
        github.com/stashapp/stash/internal/api/generated_exec.go:62679 +0x270
github.com/stashapp/stash/internal/api.(*executableSchema).Exec.func1({0x7fe462af4e60?, 0xc0012241b0?})
        github.com/stashapp/stash/internal/api/generated_exec.go:8300 +0x5b
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x7fe462af4e60, 0xc0012241b0})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:106 +0x2b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x7fe462af4e60?, 0xc0012241b0?}, 0x7fe4628a1ba0?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:66 +0x26
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x7fe462af4e60, 0xc001224150})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:105 +0x113
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({}, {0x7fe462af2650, 0xc000baf810}, 0xc0006d2900, {0x7fe462af2200, 0xc000a2a140})
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/transport/http_post.go:52 +0x308
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0004ae720, {0x7fe462af2650, 0xc000baf810}, 0xc0006d2900)
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/server.go:120 +0x212
github.com/stashapp/stash/internal/api.Initialize.func3({0x7fe462af2650, 0xc000baf810}, 0xc00018a730?)
        github.com/stashapp/stash/internal/api/server.go:170 +0xe5
net/http.HandlerFunc.ServeHTTP(0x7fe46290ca40?, {0x7fe462af2650?, 0xc000baf810?}, 0xc00079079d?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000a26120, {0x7fe462af2650, 0xc000baf810}, 0xc0019b1f00)
        github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x236
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af2650?, 0xc000baf810?}, 0x7fe463450ab0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api/loaders.Middleware.Middleware.func1({0x7fe462af2650, 0xc000baf810}, 0xc0019b1e00)
        github.com/stashapp/stash/internal/api/loaders/dataloaders.go:150 +0xae6
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af2650?, 0xc000baf810?}, 0x7fe4634506a0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.BaseURLMiddleware.func1({0x7fe462af2650, 0xc000baf810}, 0xc0019b1d00)
        github.com/stashapp/stash/internal/api/server.go:586 +0x35c
net/http.HandlerFunc.ServeHTTP(0x7fe4608605b8?, {0x7fe462af2650?, 0xc000baf810?}, 0xc000baf810?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.StripSlashes.func1({0x7fe462af2650, 0xc000baf810}, 0xc0019b1d00)
        github.com/go-chi/chi/v5@v5.0.10/middleware/strip.go:30 +0x139
net/http.HandlerFunc.ServeHTTP(0xc000278bc0?, {0x7fe462af2650?, 0xc000baf810?}, 0xc000bd3dc0?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1({0x7fe462af4240?, 0xc000bd3dc0}, 0xc0019b1d00)
        github.com/go-chi/chi/v5@v5.0.10/middleware/compress.go:213 +0x271
net/http.HandlerFunc.ServeHTTP(0x7fe462a03ee0?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0x16?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.SecurityHeadersMiddleware.func1({0x7fe462af4240, 0xc000bd3dc0}, 0x30?)
        github.com/stashapp/stash/internal/api/server.go:554 +0xf4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0xf8?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0x7fe462af4240?, 0xc000bd3dc0?}, 0x7fe4626ec901?)
        github.com/go-chi/chi/v5@v5.0.10/middleware/recoverer.go:45 +0x83
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0x7fe4626ec9a0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/pkg/session.(*Store).VisitedPluginHandler.func1.1({0x7fe462af4240, 0xc000bd3dc0}, 0xc0019b1c00)
        github.com/stashapp/stash/pkg/session/plugin.go:39 +0x20d
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0x7fe4626ec9b8?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.authenticateHandler.func1.1({0x7fe462af4240, 0xc000bd3dc0}, 0xc0019b1b00)
        github.com/stashapp/stash/internal/api/authentication.go:109 +0x503
net/http.HandlerFunc.ServeHTTP(0xc000a2a0a0?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0xc0019b1b00?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x7fe462af4240, 0xc000bd3dc0}, 0xc0019b1b00)
        github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0xf8?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Heartbeat.func1.1({0x7fe462af4240, 0xc000bd3dc0}, 0x7fe463450301?)
        github.com/go-chi/chi/v5@v5.0.10/middleware/heartbeat.go:21 +0x1b3
net/http.HandlerFunc.ServeHTTP(0x7fe462af4db8?, {0x7fe462af4240?, 0xc000bd3dc0?}, 0x7fe463450330?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000a26120, {0x7fe462af4240, 0xc000bd3dc0}, 0xc0019b1a00)
        github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x310
net/http.serverHandler.ServeHTTP({0x7fe462af0410?}, {0x7fe462af4240, 0xc000bd3dc0}, 0xc0019b1a00)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000d0ca00, {0x7fe462af4e60, 0xc000d080f0})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db
goroutine 1019027 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/stashapp/stash/internal/api.Initialize.func1({0x0?, 0x20?}, {0x7fe46291b500?, 0x7fe463451230})
        github.com/stashapp/stash/internal/api/server.go:120 +0x89
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x7fe460b9c7ac?, {0x7fe462af4e60, 0xc000d44a50}, {0x7fe46291b500?, 0x7fe463451230?})
        github.com/99designs/gqlgen@v0.17.2/graphql/context_operation.go:114 +0x3e
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages.func1()
        github.com/stashapp/stash/internal/api/generated_exec.go:32907 +0x6a
panic({0x7fe46291b500, 0x7fe463451230})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/pkg/txn.withTxn.func1()
        github.com/stashapp/stash/pkg/txn/transaction.go:68 +0x2fc
panic({0x7fe46291b500, 0x7fe463451230})
        runtime/panic.go:884 +0x212
github.com/stashapp/stash/internal/api.(*queryResolver).FindImages.func1({0x7fe462af4e60, 0xc000d44ed0})
        github.com/stashapp/stash/internal/api/resolver_query_find_image.go:110 +0x30f
github.com/stashapp/stash/pkg/txn.withTxn({0x7fe462af4e60, 0xc000d44a50}, {0x7fe462af55d0, 0xc0000422d0}, 0xc001199b98, 0x0?, 0x1)
        github.com/stashapp/stash/pkg/txn/transaction.go:92 +0x17b
github.com/stashapp/stash/pkg/txn.WithReadTxn(...)
        github.com/stashapp/stash/pkg/txn/transaction.go:52
github.com/stashapp/stash/pkg/models.(*Repository).WithReadTxn(...)
        github.com/stashapp/stash/pkg/models/repository.go:37
github.com/stashapp/stash/internal/api.(*Resolver).withReadTxn(0x8?, {0x7fe462af4e60, 0xc000d44a50}, 0xc002925400?)
        github.com/stashapp/stash/internal/api/resolver.go:128 +0x65
github.com/stashapp/stash/internal/api.(*queryResolver).FindImages(0x6?, {0x7fe462af4e60?, 0xc000d44a50?}, 0xc001199c98?, {0x0?, 0x7fe46290d940?, 0x20?}, {0x0, 0x0, 0x0}, ...)
        github.com/stashapp/stash/internal/api/resolver_query_find_image.go:64 +0x14b
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages.func2({0x7fe462af4e60?, 0xc000d44a50})
        github.com/stashapp/stash/internal/api/generated_exec.go:32929 +0x210
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x7fe462af4e60?, 0xc000d44a50?}, 0xc000d44a50?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:72 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Query_findImages(0xc00099bde0, {0x7fe462af4e60, 0xc000d44a20}, {0xc000dfe800?, {0xc0012cee10?, 0x4?, 0xc000599f80?}})
        github.com/stashapp/stash/internal/api/generated_exec.go:32927 +0x2e7
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func37({0x7fe462af4e60?, 0xc000d44a20?})
        github.com/stashapp/stash/internal/api/generated_exec.go:61539 +0xae
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x7fe462af4e60?, 0xc000d44a20?}, 0xc00099be10?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:69 +0x26
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func38({0x7fe462af4e60?, 0xc000d44a20?})
        github.com/stashapp/stash/internal/api/generated_exec.go:61547 +0x32
github.com/stashapp/stash/internal/api.(*executionContext)._Query.func39()
        github.com/stashapp/stash/internal/api/generated_exec.go:61551 +0x25
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc0012cee60)
        github.com/99designs/gqlgen@v0.17.2/graphql/fieldset.go:34 +0x96
github.com/stashapp/stash/internal/api.(*executionContext)._Query(0xc00099bde0, {0x7fe462af4e60, 0xc000d44990}, {0xc0018e97e0, 0x1, 0x1})
        github.com/stashapp/stash/internal/api/generated_exec.go:62679 +0x270
github.com/stashapp/stash/internal/api.(*executableSchema).Exec.func1({0x7fe462af4e60?, 0xc000d44990?})
        github.com/stashapp/stash/internal/api/generated_exec.go:8300 +0x5b
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x7fe462af4e60, 0xc000d44990})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:106 +0x2b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x7fe462af4e60?, 0xc000d44990?}, 0x7fe4628a1ba0?)
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:66 +0x26
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x7fe462af4e60, 0xc000d44930})
        github.com/99designs/gqlgen@v0.17.2/graphql/executor/executor.go:105 +0x113
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({}, {0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5600, {0x7fe462af2200, 0xc000a2a140})
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/transport/http_post.go:52 +0x308
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0004ae720, {0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5600)
        github.com/99designs/gqlgen@v0.17.2/graphql/handler/server.go:120 +0x212
github.com/stashapp/stash/internal/api.Initialize.func3({0x7fe462af2650, 0xc0012cedc0}, 0xc00064c280?)
        github.com/stashapp/stash/internal/api/server.go:170 +0xe5
net/http.HandlerFunc.ServeHTTP(0x7fe46290ca40?, {0x7fe462af2650?, 0xc0012cedc0?}, 0xc000a1166d?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000a26120, {0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5500)
        github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x236
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af2650?, 0xc0012cedc0?}, 0x7fe463450ab0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api/loaders.Middleware.Middleware.func1({0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5400)
        github.com/stashapp/stash/internal/api/loaders/dataloaders.go:150 +0xae6
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af2650?, 0xc0012cedc0?}, 0x7fe4634506a0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.BaseURLMiddleware.func1({0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5300)
        github.com/stashapp/stash/internal/api/server.go:586 +0x35c
net/http.HandlerFunc.ServeHTTP(0x7fe4608621d8?, {0x7fe462af2650?, 0xc0012cedc0?}, 0xc0012cedc0?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.StripSlashes.func1({0x7fe462af2650, 0xc0012cedc0}, 0xc0016a5300)
        github.com/go-chi/chi/v5@v5.0.10/middleware/strip.go:30 +0x139
net/http.HandlerFunc.ServeHTTP(0xc000278bc0?, {0x7fe462af2650?, 0xc0012cedc0?}, 0xc000db29a0?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1({0x7fe462af4240?, 0xc000db29a0}, 0xc0016a5300)
        github.com/go-chi/chi/v5@v5.0.10/middleware/compress.go:213 +0x271
net/http.HandlerFunc.ServeHTTP(0x7fe462a03ee0?, {0x7fe462af4240?, 0xc000db29a0?}, 0x16?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.SecurityHeadersMiddleware.func1({0x7fe462af4240, 0xc000db29a0}, 0x30?)
        github.com/stashapp/stash/internal/api/server.go:554 +0xf4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe462af4240?, 0xc000db29a0?}, 0xf8?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0x7fe462af4240?, 0xc000db29a0?}, 0x7fe4626ec901?)
        github.com/go-chi/chi/v5@v5.0.10/middleware/recoverer.go:45 +0x83
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af4240?, 0xc000db29a0?}, 0x7fe4626ec9a0?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/pkg/session.(*Store).VisitedPluginHandler.func1.1({0x7fe462af4240, 0xc000db29a0}, 0xc0016a5200)
        github.com/stashapp/stash/pkg/session/plugin.go:39 +0x20d
net/http.HandlerFunc.ServeHTTP(0x7fe462af4e60?, {0x7fe462af4240?, 0xc000db29a0?}, 0x7fe4626ec9b8?)
        net/http/server.go:2109 +0x2f
github.com/stashapp/stash/internal/api.authenticateHandler.func1.1({0x7fe462af4240, 0xc000db29a0}, 0xc0016a5100)
        github.com/stashapp/stash/internal/api/authentication.go:109 +0x503
net/http.HandlerFunc.ServeHTTP(0xc000a2a0a0?, {0x7fe462af4240?, 0xc000db29a0?}, 0xc0016a5100?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x7fe462af4240, 0xc000db29a0}, 0xc0016a5100)
        github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe462af4240?, 0xc000db29a0?}, 0xf8?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Heartbeat.func1.1({0x7fe462af4240, 0xc000db29a0}, 0x7fe463450301?)
        github.com/go-chi/chi/v5@v5.0.10/middleware/heartbeat.go:21 +0x1b3
net/http.HandlerFunc.ServeHTTP(0x7fe462af4db8?, {0x7fe462af4240?, 0xc000db29a0?}, 0x7fe463450330?)
        net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000a26120, {0x7fe462af4240, 0xc000db29a0}, 0xc0016a5000)
        github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x310
net/http.serverHandler.ServeHTTP({0x7fe462af0410?}, {0x7fe462af4240, 0xc000db29a0}, 0xc0016a5000)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000c3e320, {0x7fe462af4e60, 0xc000d080f0})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db

``` 
</details>

Settings > Logs is showing:
`2024-04-11 17:43:42 Error runtime error: invalid memory address or nil pointer dereference`

<details>
<summary>The offending Post Request from F12 failing with net::ERR_CONNECTION_CLOSED</summary>
```
{
    "operationName": "FindTags",
    "variables": {
        "filter": {
            "q": "redd",
            "page": 1,
            "per_page": 40,
            "sort": "name",
            "direction": "ASC"
        },
        "tag_filter": {}
    },
    "query": "query FindTags($filter: FindFilterType, $tag_filter: TagFilterType) {\n  findTags(filter: $filter, tag_filter: $tag_filter) {\n    count\n    tags {\n      ...TagData\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment TagData on Tag {\n  id\n  name\n  description\n  aliases\n  ignore_auto_tag\n  image_path\n  scene_count\n  scene_count_all: scene_count(depth: -1)\n  scene_marker_count\n  scene_marker_count_all: scene_marker_count(depth: -1)\n  image_count\n  image_count_all: image_count(depth: -1)\n  gallery_count\n  gallery_count_all: gallery_count(depth: -1)\n  performer_count\n  performer_count_all: performer_count(depth: -1)\n  parents {\n    ...SlimTagData\n    __typename\n  }\n  children {\n    ...SlimTagData\n    __typename\n  }\n  __typename\n}\n\nfragment SlimTagData on Tag {\n  id\n  name\n  aliases\n  image_path\n  parent_count\n  child_count\n  __typename\n}"
}
```
</details>

**Stash Version: (from Settings -> About):**
v0.25.1
Build hash:
bf7cb78d
Build time:
2024-03-13 03:30:08

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu Server 22.04
 - Browser: Brave
 - Version 1.64.116

**Additional context**
Total Tag count is 1835
Any hints or suggestions as to what's going on are appreciated.

EDIT: May be related to #4693
EDIT: After some more experimenting I found that the issue is not confined to filtering the mentioned tags. Even loading the Image page with the default view (`/images?sortby=random_77844700&disp=2`) or filtering by path (`/images?c=("type":"path","value":"actorA","modifier":"INCLUDES")&sortby=path&disp=2`) returns the failed to fetch error.

**Comment by Written2001** [comment]
The issue no longer persists. I noticed a misbehaving .mp4 file within one of my galleries. I can't remember the exact error message from the logs but it was something along the lines of: "Error ffprobe... something something"

I deleted and cleaned the file manually and the problem above was gone.
