### ISSUE TITLE
[Bug Report] Import via CSV does not currently work due to change in height variable

### ISSUE THREAD

**Issue by nothing2obvi** [stashapp/stash#4846]
**Describe the bug**
The instructions on [this page](https://docs.stashapp.cc/advanced-tutorials/importing-via-csv-using-gql-iterate/) used to work for me, but it's been several months and now they do not, as it seems there is a change in the height variable and perhaps more. Please update the instructions or let me know what I'm doing wrong.

This is the error:
```
Something went wrong while running your queries.
ClientError: Field "height" is not defined by type "PerformerCreateInput". Did you mean "weight" or "height_cm"?: {"response":{"errors":[{"message":"Field \"height\" is not defined by type \"PerformerCreateInput\". Did you mean \"weight\" or \"height_cm\"?","locations":[{"line":28,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"aliases\" is not defined by type \"PerformerCreateInput\".","locations":[{"line":34,"column":7}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null,"status":422,"headers":{}},"request":{"query":"mutation PerformerCreate(\n  $name: String!\n  $url: String\n  $birthdate: String\n  $ethnicity: String\n  $country: String\n  $eye_color: String\n  $height: String\n  $measurements: String\n  $fake_tits: String\n  $career_length: String\n  $tattoos: String\n  $piercings: String\n  $aliases: String\n  $twitter: String\n  $instagram: String\n  $favorite: Boolean\n  $image: String\n) {\n  performerCreate(\n    input: {\n      name: $name\n      url: $url\n      birthdate: $birthdate\n      ethnicity: $ethnicity\n      country: $country\n      eye_color: $eye_color\n      height: $height\n      measurements: $measurements\n      fake_tits: $fake_tits\n      career_length: $career_length\n      tattoos: $tattoos\n      piercings: $piercings\n      aliases: $aliases\n      twitter: $twitter\n      instagram: $instagram\n      favorite: $favorite\n      image: $image\n    }\n  ) {\n    id\n  }\n}\n","variables":{"name":"Brenna McKenna"}}}
    at /usr/local/lib/node_modules/@efstajas/gql-iterate/node_modules/graphql-request/dist/index.js:341:31
    at step (/usr/local/lib/node_modules/@efstajas/gql-iterate/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/usr/local/lib/node_modules/@efstajas/gql-iterate/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/usr/local/lib/node_modules/@efstajas/gql-iterate/node_modules/graphql-request/dist/index.js:35:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    errors: [ [Object], [Object] ],
    data: null,
    status: 422,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: 'mutation PerformerCreate(\n' +
      '  $name: String!\n' +
      '  $url: String\n' +
      '  $birthdate: String\n' +
      '  $ethnicity: String\n' +
      '  $country: String\n' +
      '  $eye_color: String\n' +
      '  $height: String\n' +
      '  $measurements: String\n' +
      '  $fake_tits: String\n' +
      '  $career_length: String\n' +
      '  $tattoos: String\n' +
      '  $piercings: String\n' +
      '  $aliases: String\n' +
      '  $twitter: String\n' +
      '  $instagram: String\n' +
      '  $favorite: Boolean\n' +
      '  $image: String\n' +
      ') {\n' +
      '  performerCreate(\n' +
      '    input: {\n' +
      '      name: $name\n' +
      '      url: $url\n' +
      '      birthdate: $birthdate\n' +
      '      ethnicity: $ethnicity\n' +
      '      country: $country\n' +
      '      eye_color: $eye_color\n' +
      '      height: $height\n' +
      '      measurements: $measurements\n' +
      '      fake_tits: $fake_tits\n' +
      '      career_length: $career_length\n' +
      '      tattoos: $tattoos\n' +
      '      piercings: $piercings\n' +
      '      aliases: $aliases\n' +
      '      twitter: $twitter\n' +
      '      instagram: $instagram\n' +
      '      favorite: $favorite\n' +
      '      image: $image\n' +
      '    }\n' +
      '  ) {\n' +
      '    id\n' +
      '  }\n' +
      '}\n',
    variables: {
      name: 'Some Performer',
      url: undefined,
      birthdate: undefined,
      ethnicity: undefined,
      country: undefined,
      eye_color: undefined,
      height: undefined,
      measurements: undefined,
      fake_tits: undefined,
      career_length: undefined,
      tattoos: undefined,
      piercings: undefined,
      aliases: undefined,
      twitter: undefined,
      instagram: undefined,
      favorite: undefined,
      image: undefined
    }
  }
}
```

This is my `performers.gql` file:
```
mutation PerformerCreate(
  $name: String!
  $url: String
  $birthdate: String
  $ethnicity: String
  $country: String
  $eye_color: String
  $height: String
  $measurements: String
  $fake_tits: String
  $career_length: String
  $tattoos: String
  $piercings: String
  $aliases: String
  $twitter: String
  $instagram: String
  $favorite: Boolean
  $image: String
) {
  performerCreate(
    input: {
      name: $name
      url: $url
      birthdate: $birthdate
      ethnicity: $ethnicity
      country: $country
      eye_color: $eye_color
      height: $height
      measurements: $measurements
      fake_tits: $fake_tits
      career_length: $career_length
      tattoos: $tattoos
      piercings: $piercings
      aliases: $aliases
      twitter: $twitter
      instagram: $instagram
      favorite: $favorite
      image: $image
    }
  ) {
    id
  }
}

```

This is how my `performers.txt` file looks.
```
name,url,birthdate,ethnicity,country,eye_color,height,measurements,fake_tits,career_length,tattoos,piercings,aliases,twitter,instagram,favorite,image
Some Performer1
Some Performer2
```

**To Reproduce**
1. Follow the instructions on this page, changing `csv` to `txt` in the command.
2. Get error.

**Expected behavior**
Performers are imported into Stash.

**Stash Version: (from Settings -> About):** v0.25.1

**Desktop (please complete the following information):**
 - OS: Mac Monterey 12.7.4
 - Browser: Opera
 - Version: 109.0.5097.80

**Smartphone (please complete the following information):**
 n/a

**Comment by WithoutPants** [comment]
This is an issue for the https://github.com/stashapp/Stash-Docs repository, and not a bug in stash.

Changing `performers.gql` to have:
```
  $height: Int
```

should address the issue, though I have not tested.
