### ISSUE TITLE
[Bug Report] Can't use french accent for paths on windows (é à ç... etc...)

### ISSUE THREAD

**Issue by Boombadybyebye** [stashapp/stash#5356]
**Describe the bug**
Stash can't use paths with accents. My user account on windows has accent and it's very complicated to change.

**To Reproduce**
create a user account with french access. 

**Expected behavior**
Use the paths with accents like it should and works on windows 

**Stash Version: (from Settings -> About):
v0.27.0

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox and chrome (latests)

**Additional context**
The "?" character should be "é"

24-10-08 10:41:08Error   Scene.Update.Post [Timestamp Trade]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / Timestamp Trade] ModuleNotFoundError: No module named 'stashapi'
2024-10-08 10:41:08Error   [Plugin / Timestamp Trade]     import stashapi.log as log
2024-10-08 10:41:08Error   [Plugin / Timestamp Trade]   File "C:\Users\M�lanie\.stash\plugins\community\timestampTrade/timestampTrade.py", line 1, in <module>
2024-10-08 10:41:08Error   [Plugin / Timestamp Trade] Traceback (most recent call last):
2024-10-08 10:41:08Error   Scene.Update.Post [Tag Scenes From Performer Tags]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / Tag Scenes From Performer Tags] ModuleNotFoundError: No module named 'stashapi'
2024-10-08 10:41:08Error   [Plugin / Tag Scenes From Performer Tags]     from stashapi.stashapp import StashInterface
2024-10-08 10:41:08Error   [Plugin / Tag Scenes From Performer Tags]   File "C:\Users\M�lanie\.stash\plugins\community\tagScenesWithPerfTags/tagScenesWithPerfTags.py", line 1, in <module>
2024-10-08 10:41:08Error   [Plugin / Tag Scenes From Performer Tags] Traceback (most recent call last):
2024-10-08 10:41:08Error   Scene.Update.Post [renamerOnUpdate]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / renamerOnUpdate] ModuleNotFoundError: No module named 'requests'
2024-10-08 10:41:08Error   [Plugin / renamerOnUpdate]     import requests
2024-10-08 10:41:08Error   [Plugin / renamerOnUpdate]   File "C:\Users\M�lanie\.stash\plugins\community\renamerOnUpdate/renamerOnUpdate.py", line 12, in <module>
2024-10-08 10:41:08Error   [Plugin / renamerOnUpdate] Traceback (most recent call last):
2024-10-08 10:41:08Error   Scene.Update.Post [RenameFile]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / RenameFile] ModuleNotFoundError: No module named 'requests'
2024-10-08 10:41:08Error   [Plugin / RenameFile]     import os, sys, shutil, json, requests, hashlib, pathlib, logging
2024-10-08 10:41:08Error   [Plugin / RenameFile]   File "C:\Users\M�lanie\.stash\plugins\community\renamefile/renamefile.py", line 5, in <module>
2024-10-08 10:41:08Error   [Plugin / RenameFile] Traceback (most recent call last):
2024-10-08 10:41:08Error   Scene.Update.Post [Misc Tags]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / Misc Tags] ModuleNotFoundError: No module named 'stashapi'
2024-10-08 10:41:08Error   [Plugin / Misc Tags]     import stashapi.log as log
2024-10-08 10:41:08Error   [Plugin / Misc Tags]   File "C:\Users\M�lanie\.stash\plugins\community\miscTags/miscTags.py", line 1, in <module>
2024-10-08 10:41:08Error   [Plugin / Misc Tags] Traceback (most recent call last):
2024-10-08 10:41:08Error   Scene.Update.Post [The Porn DB Markers]: returned error: exit status 1
2024-10-08 10:41:08Error   [Plugin / The Porn DB Markers] ModuleNotFoundError: No module named 'stashapi'
2024-10-08 10:41:08Error   [Plugin / The Porn DB Markers]     import stashapi.log as log
2024-10-08 10:41:08Error   [Plugin / The Porn DB Markers]   File "C:\Users\M�lanie\.stash\plugins\community\TPDBMarkers/tpdbMarkers.py", line 1, in <module>
2024-10-08 10:41:08Error   [Plugin / The Porn DB Markers] Traceback (most recent call last):

**Comment by feederbox826** [comment]
> 2024-10-08 10:41:08Error [Plugin / Timestamp Trade] ModuleNotFoundError: No module named 'stashapi'
this is a different issue

`pip install stashapp-tools`

the unicode loss is in browser and in the font

**Comment by Boombadybyebye** [comment]
pip install stashapp-tools
Requirement already satisfied: stashapp-tools in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (0.2.55)
Requirement already satisfied: requests in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (from stashapp-tools) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (from requests->stashapp-tools) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (from requests->stashapp-tools) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (from requests->stashapp-tools) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mélanie\appdata\local\programs\python\python313\lib\site-packages (from requests->stashapp-tools) (2024.8.30)
